#!/usr/bin/env bun
/**
 * Open a GitHub pull request from the issue branch into main, then post the
 * PR URL as a comment on the Jira ticket so reviewers find it from Jira.
 *
 * Reads:
 *   $ARTIFACTS_DIR/trigger-payload.json — issue_key, summary
 *   $ARTIFACTS_DIR/task.raw.json — full task fields (description, ACs)
 *   $ARTIFACTS_DIR/branch-name.txt — current branch (set by checkout-branch)
 *
 * stdout: { pr_url, pr_number, branch }
 */
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const artifactsDir = process.env.ARTIFACTS_DIR;
if (!artifactsDir) {
  console.error('ARTIFACTS_DIR not set');
  process.exit(1);
}

interface TriggerPayload {
  issue_key: string;
  summary?: string;
}
const trigger: TriggerPayload = JSON.parse(await readFile(`${artifactsDir}/trigger-payload.json`, 'utf8'));

let taskTitle = trigger.summary ?? trigger.issue_key;
let taskDescription = '';
try {
  const task = JSON.parse(await readFile(`${artifactsDir}/task.raw.json`, 'utf8')) as {
    fields: { summary: string; description?: unknown };
  };
  taskTitle = task.fields.summary;
  // ADF flatten — same simple version as elsewhere
  const adfToText = (node: unknown): string => {
    if (node == null) return '';
    if (typeof node === 'string') return node;
    if (typeof node !== 'object') return String(node);
    const obj = node as { type?: string; text?: string; content?: unknown[] };
    const parts: string[] = [];
    if (obj.type === 'text' && typeof obj.text === 'string') parts.push(obj.text);
    if (Array.isArray(obj.content)) {
      for (const child of obj.content) parts.push(adfToText(child));
      if (obj.type !== 'text' && obj.type !== undefined) parts.push('\n\n');
    }
    return parts.join('');
  };
  taskDescription = adfToText(task.fields.description).trim();
} catch {
  // task.raw.json might be missing on resumed runs; fall back to trigger summary
}

async function git(...args: string[]): Promise<string> {
  const { stdout } = await execFileAsync('git', args, { cwd: process.cwd() });
  return stdout.trim();
}

// Read the actual current branch from the worktree, not a stale artifact file.
const branch = await git('rev-parse', '--abbrev-ref', 'HEAD');

// Push the branch to make sure origin has the latest commits before opening the PR.
console.log(`Pushing ${branch} to origin to ensure remote is up to date...`);
try {
  await git('push', '-u', 'origin', branch);
} catch (e) {
  const err = e as { stderr?: string; message?: string };
  console.error(`Failed to push ${branch}: ${err.stderr ?? err.message}`);
  process.exit(1);
}

const baseUrl = process.env.JIRA_BASE_URL ?? '';
const ticketLink = baseUrl ? `${baseUrl}/browse/${trigger.issue_key}` : trigger.issue_key;

// Compose PR body
const bodyLines: string[] = [];
bodyLines.push(`Implements [${trigger.issue_key}](${ticketLink}): **${taskTitle}**`);
bodyLines.push('');
if (taskDescription) {
  bodyLines.push('## Task Description');
  bodyLines.push('');
  bodyLines.push(taskDescription);
  bodyLines.push('');
}
bodyLines.push('## Validation');
bodyLines.push('');
bodyLines.push('All quality gates (lint, typecheck, scoped unit tests, scoped E2E tests) passed locally before this PR was opened.');
bodyLines.push('');
bodyLines.push('---');
bodyLines.push('');
bodyLines.push('🤖 *Autonomously generated by the Archon pipeline. Tests written by `task-tests`; implementation written by `task-implement`.*');

const body = bodyLines.join('\n');

// Open PR via gh
console.log(`Opening PR from ${branch} → main...`);
let prUrl = '';
let prNumber = 0;
try {
  const { stdout } = await execFileAsync(
    'gh',
    [
      'pr',
      'create',
      '--base',
      'main',
      '--head',
      branch,
      '--title',
      `${trigger.issue_key}: ${taskTitle}`,
      '--body',
      body,
    ],
    { cwd: process.cwd(), maxBuffer: 50 * 1024 * 1024 }
  );
  prUrl = stdout.trim().split('\n').pop() ?? '';
  console.log(`PR opened: ${prUrl}`);
  // Extract number from URL (last path segment)
  const m = prUrl.match(/\/pull\/(\d+)/);
  if (m) prNumber = parseInt(m[1], 10);
} catch (e) {
  const err = e as { stdout?: string; stderr?: string; message?: string };
  // Common case: PR already exists for this branch — recover the URL via gh pr view
  if ((err.stderr ?? '').includes('already exists')) {
    console.log('PR already exists for this branch; fetching its URL...');
    const { stdout } = await execFileAsync('gh', ['pr', 'view', '--json', 'url,number'], {
      cwd: process.cwd(),
    });
    const parsed = JSON.parse(stdout) as { url: string; number: number };
    prUrl = parsed.url;
    prNumber = parsed.number;
    console.log(`Existing PR: ${prUrl}`);
  } else {
    console.error(`gh pr create failed: ${err.stderr ?? err.message}`);
    process.exit(1);
  }
}

// Comment on the Jira ticket
console.log('Posting PR link as a Jira comment...');
const commentInput = JSON.stringify({
  action: 'addComment',
  issueKey: trigger.issue_key,
  text: `PR opened: ${prUrl}`,
});
try {
  await execFileAsync('bun', ['/home/user/Archon/.archon/scripts/jira-tool.js', commentInput], {
    maxBuffer: 50 * 1024 * 1024,
  });
  console.log('Jira comment posted.');
} catch (e) {
  const err = e as { stdout?: string; message?: string };
  console.error(`Failed to post Jira comment (PR is still open): ${err.stdout ?? err.message}`);
  // Don't fail the whole node — the PR exists, the Jira comment is a nice-to-have.
}

await writeFile(
  `${artifactsDir}/pr-info.json`,
  JSON.stringify({ pr_url: prUrl, pr_number: prNumber, branch }, null, 2)
);

process.stdout.write('\n' + JSON.stringify({ pr_url: prUrl, pr_number: prNumber, branch }));
